/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.pfm.controller;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import com.pfm.dto.Investment;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "com.pfm.codegen.languages.SpringCodegen", date = "2018-05-19T00:16:19.389Z")

@Api(value = "investment", description = "the investment API")
public interface InvestmentApi {

    @ApiOperation(value = "delete investment.", nickname = "investmentDeleteDelete", notes = "delete an existing investment by specifying an investment_id.", tags={ "investment", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "investment successfully delelted from database.") })
    @RequestMapping(value = "/investment/delete",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> investmentDeleteDelete(@ApiParam(value = "investment object to delete from database." ,required=true )  @Valid @RequestBody String body);


    @ApiOperation(value = "new investment.", nickname = "investmentNewPost", notes = "create a new investment for an existing investor.", response = Investment.class, responseContainer = "List", tags={ "investment", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "investment successfully added to database.", response = Investment.class, responseContainer = "List") })
    @RequestMapping(value = "/investment/new",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<List<Investment>> investmentNewPost(@ApiParam(value = "investment object to add to database." ,required=true )  @Valid @RequestBody Investment body);

}
